version: 2.1

jobs:
  build-learning-angular:
    working_directory: ~/learning-angular
    docker:
      - image: circleci/node:14.14-browsers
    steps:
      - checkout
      - restore_cache:
          key: learning-angular-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: install
          command: npm install
      - save_cache:
          key: learning-angular-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - 'node_modules'
      - run:
          name: build
          command: npm run build:ci

  test-learning-angular:
    working_directory: ~/learning-angular
    docker:
      - image: circleci/node:14.14-browsers
    steps:
      - checkout
      - restore_cache:
          key: learning-angular-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: install
          command: npm install
      - save_cache:
          key: learning-angular-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - 'node_modules'
      - run:
          name: test:unit
          command: npm run test:unit
      - run:
          name: test:e2e
          command: npm run test:e2e
      - run:
          name: codecov
          command: npm run codecov

workflows:
  version: 2
  learning-angular-workflow:
    jobs:
      - build-learning-angular
      - test-learning-angular:
          requires:
            - build-learning-angular
