version: 2.1

jobs:
  build-learning-angular-lib:
    working_directory: ~/learning-angular
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: learning-angular-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: learning-angular-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - 'node_modules'
      - run:
          name: build
          command: npm run build:learning-angular-lib

  build-learning-angular:
    working_directory: ~/learning-angular
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: learning-angular-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: learning-angular-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - 'node_modules'
      - run:
          name: build learning-angular-lib
          command: npm run build:learning-angular-lib
      - run:
          name: build
          command: npm run build

  test-learning-angular:
    working_directory: ~/learning-angular
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: learning-angular-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: install
          command: npm install
      - save_cache:
          key: learning-angular-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - 'node_modules'
      - run:
          name: build learning-angular-lib
          command: npm run build:learning-angular-lib
      - run:
          name: unit test
          command: npm run test
      - run:
          name: e2e test
          command: npm run e2e
      - run:
          name: codecov
          command: npm run codecov

  test-learning-angular-lib:
    working_directory: ~/learning-angular
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: learning-angular-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: learning-angular-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - 'node_modules'
      - run:
          name: unit test
          command: npm run test:learning-angular-lib

workflows:
  version: 2
  learning-angular-workflow:
    jobs:
      - build-learning-angular-lib
      - build-learning-angular
      - test-learning-angular-lib:
          requires:
            - build-learning-angular-lib
      - test-learning-angular:
          requires:
            - build-learning-angular
