version: 2.0

jobs:
  build:
    working_directory: ~/learning-angular

    docker:
      - image: circleci/node:10-browsers

    steps:
      - checkout

      - restore_cache:
          key: learning-angular-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - run: npm install

      - save_cache:
          key: learning-angular-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - 'node_modules'

      - run:
          name: build
          command: npm run build

      - run:
          name: unit test
          command: npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessNoSandbox --code-coverage

      - run:
          name: e2e test
          command: npm run e2e -- --protractor-config=e2e/protractor.ci.conf.js --port 42001
