version: 2
jobs:
  build:
    working_directory: ~/learning-angular
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: learning-angular-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: learning-angular-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - 'node_modules'
      - run: npm run build
      - run: npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessNoSandbox --code-coverage
      - run: npm run e2e -- --protractor-config=e2e/protractor.ci.conf.js --port 42001
      - run:
          name: Coveralls
          command: cat ./coverage/learning-angular/lcov.info  | ./node_modules/coveralls/bin/coveralls.js
